# action.yml
name: 'Run FusionAuth'
author: 'Dan Moore'
description: 'Stand up a FusionAuth instance for integration testing'
inputs:
  kickstart-file-name:  # id of input
    description: 'Name of the kickstart file'
    required: true
    default: 'kickstart.json'
runs:
  using: 'composite'
  steps: 
    - run: echo Hello ${{ inputs.kickstart-file-name }}.
      shell: bash
    - run: docker-compose up
      env:
        DATABASE_ROOT_USERNAME=postgres
        DATABASE_ROOT_PASSWORD=postgres
        DATABASE_USERNAME=postgres
        DATABASE_PASSWORD=postgres
        FUSIONAUTH_APP_MEMORY=512M
        FUSIONAUTH_APP_RUNTIME_MODE=development
        FUSIONAUTH_APP_KICKSTART_FILE=/usr/local/fusionauth/kickstart/kickstart.json -e 
        SEARCH_TYPE=database
      shell: bash
