# action.yml
name: 'Run FusionAuth'
author: 'Dan Moore'
description: 'Stand up a FusionAuth instance for integration testing'
inputs:
  kickstart-file-name:  # id of input
    description: 'Name of the kickstart file'
    required: true
    default: 'kickstart.json'
runs:
  using: 'composite'
  steps: 
    - run: echo Hello ${{ inputs.kickstart-file-name }}.
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash
    - run: docker-compose up
      shell: bash
